language: go

matrix:
  fast_finish: true
  include:
    - go: 1.10.x
    - go: 1.11.x
      env: GO111MODULE=on
    - go: master
      env: GO111MODULE=on
  allow_failures:
    - go: master

script: go test

jobs:
  include:
    - stage: build
      go: 1.11.x
      env: GO111MODULE=on
      script: CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o ethtool-exporter .
